apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset-example
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/baloise-incubator/appset-example.git
        revision: HEAD
        pathParamPrefix: ""
        directories:
          - path: "*"
  template:
    metadata:
      name: '{{path.basenameNormalized}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/baloise-incubator/appset-example.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true